name: Serenity BDD Report & Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - develop
      - feature/setup-api-framework
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Set up Java 17 (Temurin)
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.8

      - name: Run Tests and Generate Serenity Reports
        run: gradle clean test aggregate -Dheadless.mode=true
      
      - name: Deploy Serenity Reports to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/site/serenity
